run:
  name: "ABCTEST" # give your model a name
  base_dir: "trained_models" # this is where you want to save the trained model
  gpu: "3" # check GPU availabiliy with nvidia-smi
  seed: 42

data:
  train: ["Simulated_Lesion_double_2_normalized_tMPPCA_5D", "Simulated_Lesion_double_3_normalized_tMPPCA_5D", "Simulated_Lesion_double_4_normalized_tMPPCA_5D", "Simulated_Lesion_double_5_normalized_tMPPCA_5D", "Simulated_Lesion_double_6_normalized_tMPPCA_5D"]
  val:   ["Simulated_Lesion_double_1_normalized_tMPPCA_5D"]

  image_axes: [0, 1, 3]  # those are the 2 axes for the 2D network, you can also specify 3 axes, and a 3D Network is initiated. 3, 4 is typically FID and repetition
  channel_axis: 4     # number or null.  if you want you can use the channel axis so the network uses more information simultaneously
  fourier_axes: [3]   # before training, this axis is fourier transformed: Typicalyl FID -> Spectrum
  num_samples: 20 #10000  # how many voxels are chosen per epoch
  val_samples: 4 #2000

  normalization: True   # data is automatically normalized

masking:
  masked_axes: [4]    # global data axes to be masked; can contain one axis (1D mask) or two axes (2D mask)
  num_pixels: 1       # careful: this means masked pixels in the 1D oder 2D mask; the mask is then replicated across the other dimensions
  window_size: 3      # how big is the windows from which neighbors are drawn

model:
  features: [32, 64, 128, 256, 512]

optim:
  lr: 0.001           # intial learning rate
  factor: 0.5         # learning rate is multiplied by factor after step_size epochs
  step_size: 50
  min_lr: 0.00002     # once this learning rate is reached, it is not further reduced
  epochs: 500

  batch_size: 40
  num_workers: 0